# Copyright (C) 2021, RTE (http://www.rte-france.com)
# SPDX-License-Identifier: Apache-2.0

# Create two snapshots on VM test1
# Prerequisites:
# - VM cluster must be deployed
# - VM test1 must be present on the cluster

---
- name: Create snapshots snap0 and snap1 on test1
  hosts : "{{ groups.hypervisors[0] }}"
  tasks:
      - name: Create first snapshot
        cluster_vm:
            name: test1
            command: create_snapshot
            snapshot_name: snap0
      - name: Create second snapshot
        cluster_vm:
            name: test1
            command: create_snapshot
            snapshot_name: snap1
      - name: Verify creation
        cluster_vm:
            name: test1
            command: list_snapshots
        register: snap_list
        failed_when:
            - "'snap0' not in snap_list.list_snapshot"
            - "'snap1' not in snap_list.list_snapshot"
