# Copyright (C) 2021, RTE (http://www.rte-france.com)
# SPDX-License-Identifier: Apache-2.0

# Disable a VM by using the cluster_vm Ansible module
# Prerequisites:
# - VM cluster must be deployed
# - VM test0 must have been enabled on the cluster

---
- name: Disable VM test0
  hosts : "{{ groups.hypervisors[0] }}"
  tasks:
      - name: Disable VM test0
        cluster_vm:
            name: test0
            command: disable
      - name: Verify status
        cluster_vm:
            command: status
            name: test0
        register: vm_status
        failed_when: vm_status.status != "Disabled"
