# Copyright (C) 2021, RTE (http://www.rte-france.com)
# SPDX-License-Identifier: Apache-2.0

# Ansible playbook that runs Cukinia cluster tests.

---
- hosts: "{{ machines_tested | default('cluster_machines') }}"
  name: Cluster tests
  tasks:
    - name: Create temporary Cukinia directory
      tempfile:
        state: directory
        register: tmp_cukinia_dir
    - name: cluster tests
      shell:
        cmd: "cukinia -f junitxml -o {{ tmp_cukinia_dir.path }}/cukinia_cluster.xml
          /etc/cukinia/cukinia-cluster.conf || true"
    - name: Fetch result
      fetch:
        src: "{{ tmp_cukinia_dir.path }}/cukinia_cluster.xml"
        dest: "{{ cukinia_test_prefix | \
               default('.') }}/common/{{ inventory_hostname }}/cukinia_cluster.xml"
        flat: yes
