# Copyright (C) 2021, RTE (http://www.rte-france.com)
# SPDX-License-Identifier: Apache-2.0
# Deploy 4 VMs on the CI

---
- name: Prepare the CI
  hosts: localhost
  tasks:
    - name: Build the DHCP server docker image
      docker_image:
        name: "ci_dhcp_vm"
        tag: "1.0"
        state: present
        source: build
        build:
          path: "{{ ci_docker_compose_path }}/dhcp_vm"
          pull: true
          args:
            DHCP_RANGE_BEGIN: "{{ dhcp_vm_range_begin }}"
            DHCP_RANGE_END: "{{ dhcp_vm_range_end }}"
            DHCP_BIND_INTERFACE: "{{ dhcp_vm_bind_interface }}"
    - name: Start the DHCP server
      docker_container:
        recreate: true
        network_mode: host
        auto_remove: true
        state: "started"
        image: "ci_dhcp_vm:1.0"
        name: "ci_dhcp_vm"
        capabilities:
          - "net_admin"

- hosts: hypervisors
  name: Import os disk (this can be long).
  vars:
    - disk_path: >-
        {{ image_directory }}/{{ guest_image |
        default('seapath-guest-efi-image-votp.wic.qcow2') }}
    - disk_name: os
    - force: true
  roles:
    - seapath_import_vm_disk
- hosts: hypervisors
  name: Copy os disk for guest0
  vars:
    - disk_name: os
    - new_disk: os0
    - action: copy
    - force: true
  roles:
    - seapath_manage_disks
- hosts: hypervisors
  name: Copy os disk for guest1
  vars:
    - disk_name: os
    - new_disk: os1
    - action: copy
    - force: true
  roles:
    - seapath_manage_disks
- hosts: hypervisors
  name: Copy os disk for guest2
  vars:
    - disk_name: os
    - new_disk: os2
    - action: copy
    - force: true
  roles:
    - seapath_manage_disks
- hosts: hypervisors
  name: Copy os disk for guest3
  vars:
    - disk_name: os
    - new_disk: os3
    - action: copy
    - force: true
  roles:
    - seapath_manage_disks
- hosts: hypervisors
  name: Create data disk for guest0
  vars:
    - disk_name: data0
    - action: create
    - size: 5
    - size_unit: G
    - force: true
  roles:
    - seapath_manage_disks
- hosts: hypervisors
  name: Create data disk for guest1
  vars:
    - disk_name: data1
    - action: create
    - size: 5
    - size_unit: G
    - force: true
  roles:
    - seapath_manage_disks
- hosts: hypervisors
  name: Create data disk for guest2
  vars:
    - disk_name: data2
    - action: create
    - size: 5
    - size_unit: G
    - force: true
  roles:
    - seapath_manage_disks
- hosts: hypervisors
  name: Create data disk for guest3
  vars:
    - disk_name: data3
    - action: create
    - size: 5
    - size_unit: G
    - force: true
  roles:
    - seapath_manage_disks
- hosts: hypervisors
  name: Create the guest0 VM
  vars:
    - vm_name: guest0
    - state: create
    - xml_template: ../templates/vm/votp_vm_dpdk.xml.j2
    - rbd_pool: rbd
    - os_disk: os0
    - data_disk: data0
    - ovs_br: ovsbr0
    - ovs_port: 0
    - activate: 'yes'
    - mac_address: '52:54:00:ab:39:8f'
  roles:
    - seapath_vm_manage
- hosts: hypervisors
  name: Create the guest1 VM
  vars:
    - vm_name: guest1
    - state: create
    - xml_template: ../templates/vm/votp_vm_dpdk.xml.j2
    - rbd_pool: rbd
    - os_disk: os1
    - data_disk: data1
    - ovs_br: ovsbr0
    - ovs_port: 1
    - activate: 'yes'
    - mac_address: '52:54:00:66:d3:c4'
  roles:
    - seapath_vm_manage
- hosts: hypervisors
  name: Create the guest2 VM
  vars:
    - vm_name: guest2
    - state: create
    - xml_template: ../templates/vm/votp_vm_dpdk.xml.j2
    - rbd_pool: rbd
    - os_disk: os2
    - data_disk: data2
    - ovs_br: ovsbr0
    - ovs_port: 2
    - activate: 'yes'
    - mac_address: '52:54:00:dd:78:91'
  roles:
    - seapath_vm_manage
- hosts: hypervisors
  name: Create the guest3 VM
  vars:
    - vm_name: guest3
    - state: create
    - xml_template: ../templates/vm/votp_vm_dpdk.xml.j2
    - rbd_pool: rbd
    - os_disk: os3
    - data_disk: data3
    - ovs_br: ovsbr0
    - ovs_port: 3
    - activate: 'yes'
    - mac_address: '52:54:00:54:4d:e6'
  roles:
    - seapath_vm_manage


