# Copyright (C) 2021, RTE (http://www.rte-france.com)
# SPDX-License-Identifier: Apache-2.0
# This Ansible playbook start machines and ensure the PXE flash image is
# running on it.
---
- name: Prepare the CI
  hosts: localhost
  tasks:
      - name: Start the PXE server
        docker_compose:
            project_src: "{{ ci_docker_compose_path }}"
            scale:
                pxe: 1
      - name: Cut the power supply to all machines
        script: |
            ../scripts/eg_pms2_lan_driver_power.sh \
            --ip "{{ eg_ip }}" \
            --password "{{ eg_passwd }}" \
            --port "{{ item }}" \
            --state off
        with_items:
            - 1
            - 2
            - 3
            - 4
      - name: Wait one minute before power on
        pause:
            minutes: 1
      - name: Restore the power supply to all machines
        script: |
            ../scripts/eg_pms2_lan_driver_power.sh \
            --ip "{{ eg_ip }}" \
            --password "{{ eg_passwd }}" \
            --port "{{ item }}" \
            --state on
        with_items:
            - 1
            - 2
            - 3
            - 4
- name: Wait all machines have finish to boot on flash-pxe image
  hosts: pxe_machines
  tasks:
      - name: Wait for machine to be online
        wait_for_connection:
      - name: Check we have boot on the flash-pxe image
        lineinfile:
            path: /etc/os-release
            state: present
            line: ID="votp-flash"
        check_mode: true
- name: Stop the PXE server
  hosts: localhost
  tasks:
      - docker_compose:
            project_src: "{{ ci_docker_compose_path }}"
            scale:
                pxe: 0
