# Copyright (C) 2021, RTE (http://www.rte-france.com)
# SPDX-License-Identifier: Apache-2.0
# This Ansible playbook start machines and ensure the PXE flash image is
# running on it.
---
- name: Prepare the CI
  hosts: localhost
  tasks:
      - name: Start the PXE server
        docker_compose:
            project_src: "{{ ci_docker_compose_path }}"
            scale:
                pxe: 1
- import_playbook: ci_restart_machines.yaml
  vars:
      machines: pxe_machines
- name: Check all machines have boot on the flash-pxe image
  hosts: pxe_machines
  tasks:
      - name: "Check {{ inventory_hostname }} have boot on the flash-pxe image"
        lineinfile:
            path: /etc/os-release
            state: present
            line: ID="votp-flash"
        check_mode: true
- name: Stop the PXE server
  hosts: localhost
  tasks:
      - docker_compose:
            project_src: "{{ ci_docker_compose_path }}"
            scale:
                pxe: 0
